name: cat_tinder
description: "Cat Tinder"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_launcher_icons: ^0.13.1
  appinio_swiper: ^2.1.1
  cached_network_image: ^3.3.1
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon.svg
    - assets/cross.svg
    - assets/heart.svg
    - assets/home.svg

flutter_launcher_icons:
  android: "ic_launcher"
  image_path_android: "assets/icon-1028x1028.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon-1028x1028.png"
  adaptive_icon_monochrome: "assets/icon-monochrome-432x432.png"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icon.png"
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#ff81a6"
  windows:
    generate: false
  macos:
    generate: false
